### PR TITLE
Battery Overhaul

### PR DESCRIPTION
**Pull request by pablocnvs**
This PR overhauls the production of batteries, replacing the old batteries with newer ones based on current technologies and make their production be more in line with the current style of the game. The pr has been coded to ensure nobody loses the batteries they have made, so the new batteries relate to the old ones. Expect however a shift in textures, as the previous material tiers (Vanadium, Naquadria and Neutronium) have been replaced by tiers based on cell chemistry (Lithium Ion, Lithium Sulfide and Fluoride).
As a bonus, the pr gives more uses to items and fluids that have just one use, encouraging the investment in those chains.

PS: The UMV and UXV wires are a bit of a placeholder, as there is no more materials for those tiers

### CODE REVIEW

**Comment by brachy84** [comment]
If I'm not mistaken then this will delete all existing batterys from existing saves, which is obviously not good

**Comment by pablocnvs** [comment]
I'm going to retest that, but i think first time everything went ok

**Comment by pablocnvs** [comment]
Proof that no batteries are lost:





Textures have changed, but tier remains the same

**Review by hjae78 — APPROVED** [review]

**Review by Zalgo239 — APPROVED** [review]

**Review by Yefancy — APPROVED** [review]

**Review by DStrand1 — APPROVED** [review]
Looks good! At this point though, I feel we should maybe rename or even remove the config option for "GT5u ZPM/UV batteries" since they are not from GT5U anymore.

**Pull request merged**
