### PR TITLE
[FIX] advanced models+freedom wrench

### PR DESCRIPTION
**Pull request by Yefancy**
issues:
//TODO

### CODE REVIEW

**Comment by DStrand1** [comment]
I reviewed this some, and what is being fixed seems good so far, though there seems to be a lot more to do still. Whenever you feel this is closer to ready, feel free to request me for review and I can test changes more thoroughly

**Comment by Yefancy** [comment]
The compatibility with MBT could be better, but I haven't had much time to work on it recently. Submit a working version for now

**Review by TechLord22 — APPROVED** [review]

**Comment by DStrand1** [comment]
Apologies for force pushing to your branch, but I was able to resolve the git hierarchy issues and resolve a merge conflict with `build.gradle.kts`. Now I will review the code fully

**Review by DStrand1 — APPROVED** [review]
Code looks good, and from some testing done with a build of this PR, seems to fix most if not all of the issues. There are some minor points that could be better but I won't hold up the PR with code cleanliness changes. Although hopefully in the future we can figure something better out for MBT

**Pull request merged**
