### PR TITLE
Prevent JEI RecipeMap Overlaps

### PR DESCRIPTION
**Pull request by TechLord22**
Currently, the Large Mixer and Chemical Plant RecipeMaps overlap with the recipe info in JEI, as shown below. This PR changes these two RecipeMaps to be handled similarly to the Assembly Line, thus preventing the overlapping information. For future use, the logic used in the two new classes can be duplicated for any RecipeMap needing more spacing in JEI, where the Chemical Plant applies to regular RecipeMaps, and the Large Mixer applies to LargeRecipeMaps. 

Chemical Plant Before:
image

Chemical Plant After:
image

Large Mixer Before:
image

Large Mixer After:
image

### CODE REVIEW

**Review by hjae78 — APPROVED** [review]

**Comment by hjae78** [comment]
Very, very nice!

**Review by DStrand1 — CHANGES_REQUESTED** [review]
There is a lot of duplicate code here, is there not a way in the general recipe map to set an offset for the text depending on the input slots?

**Comment by TechLord22** [comment]
Updated and renamed the two classes. The new classes now both work with any RecipeMap of their equivalent type. The solution for this turned to be pretty simple, which was having a default ProgressBar texture.

**Review by DStrand1 — APPROVED** [review]
Seems a bit better, but I still feel like there is a lot of duplicate code. Though maybe this is not something that can really be helped, at least not within scope.

**Comment by huneau** [comment]
> Seems a bit better, but I still feel like there is a lot of duplicate code. Though maybe this is not something that can really be helped, at least not within scope.

yeah I agree

**Review by huneau — APPROVED** [review]

**Comment by hjae78** [comment]
addInventorySlotGroup is identical to RecipeMap I think?

**Review by Yefancy — APPROVED** [review]

**Comment by hjae78** [comment]
I think we can merge both files and only change `createUITemplate()`. Basically all we are doing is extending the window since JEI adds total energy starting from the bottom of the window as far as I can tell. I don't think there is any type of GUI math needed here

**Review by brachy84 — APPROVED** [review]

**Pull request merged**
