### PR TITLE
Mainframe resprite

### PR DESCRIPTION
**Pull request by trerri**
See title.

circuit supracausal mainframe
mainframe wetware
circuit bioware mainframe
circuit cosmic mainframe
circuit mainframe crystal
circuit mainframe micro
circuit mainframe nano
circuit mainframe optical
circuit mainframe quantum
circuit mainframe refined

### CODE REVIEW

**Review by DStrand1 — COMMENTED** [review]
Personally I am not a fan of changing these textures in any way. They take from past versions of GT, and as GTCE is primarily a rewrite of GT5 for 1.12.2, I don't see why these should be changed in the mod.

**Comment by trerri** [comment]
Counter argument: the original ones look bad, and these ones look better (subjective) as they're more consistent with the MC style. Hence, they should be changed.

**Comment by hjae78** [comment]
The mainframe sprite is very old and I think that this works better as a resource pack

**Comment by hjae78** [comment]
I'm closing this for now

**Pull request closed without merging**
