### PR TITLE
More Textures

### PR DESCRIPTION
**Pull request by TechLord22**
Textures for the following items:
1. Acrylic Yarn
2. Boron Retaining Yarn
3. Boron Saturated Yarn
4. Heavy Metal Absorbing Yarn
5. Uranium Saturated Yarn
6. Insulation Wire Assembly
7. Recursively Folded Negative Space (animated)
8. Nanotome -created by Pcm_Keywielder on discord
9. Halide Lamp Cores (all colors) - Created by @whatsapp2
10. Time Dilation Containment Unit and Contained Singularities (animated) - Created by @whatsapp2
11. Separation Electromagnet - Created by @whatsapp2
12. Low-High Frequency Laser - Created by @whatsapp2

Screenshot of my and Pcm's textures:
image

Video of Recursively Folded Negative Space:
https://user-images.githubusercontent.com/37029404/106825244-76b72e80-6652-11eb-991f-ebf241783199.mp4

Screenshots of @whatsapp2's Textures:
image
image

### CODE REVIEW

**Comment by pablocnvs** [comment]
You could add Whatsapp's images as well

**Comment by huneau** [comment]
nice job. 
Im not a huge fan of this one 
image

it seems not gregish and pixel seems .... wierd but anyway Nice job and thank a lot for your time !!!!

**Review by huneau — APPROVED** [review]

**Comment by hjae78** [comment]
@huneau Zalgo rendered that using some extremely complex physics model and is how it would actually look

**Comment by hjae78** [comment]
Good job everyone, we really, really appreciate it!

**Pull request merged**
