### PR TITLE
Textures for supracausal stuff

### PR DESCRIPTION
**Pull request by Zalgo239**
-Added wormhole generator textures
-Added neutronium sphere textures
-Added Supracausal SMDs textures

### CODE REVIEW

**Comment by hjae78** [comment]
I really like them but I feel the neutronium spheres might need some changes. Are they 32x32?

**Comment by Zalgo239** [comment]
> 
> 
> I really like them but I feel the neutronium spheres might need some changes. Are they 32x32?

They are 64x64 actually, I can probably remake those this evening to be 32x32 and a little more interesting

**Comment by hjae78** [comment]
I'd prefer if we could have them be 16x16, they would be consistent with most spherical shapes we have then

**Comment by Zalgo239** [comment]
Alright, I'll make them 16x16 then

**Comment by hjae78** [comment]
Looks great! Thank you so much!

**Pull request merged**
