### PR TITLE
Add all machine to the Processing Array,and change some Chinese translation

### PR DESCRIPTION
**Pull request by magcicada**

### CODE REVIEW

**Comment by huneau** [comment]
thanks a lot, can you solve the conflicts?

**Comment by magcicada** [comment]
My computer is no power,I will check it tomorrow

**Comment by magcicada** [comment]
It's 12:20 am GTM+8 now

**Comment by magcicada** [comment]
I need rewrite the lang file,it will upload again almost 4 hours later,Ineed to go to work.(๑•̀ㅂ•́)و✧

**Pull request closed without merging**
