### PR TITLE
Supporting GT tools in AE2

### PR DESCRIPTION
**Pull request by Yefancy**
This is a very simple coremod, almost no hacking of AE2. 
Feature: fixed an issue with NBT meta items (such as gt tools) that could not be recognized, when using JEI to import a recipe into the crafting terminal.

ae2

### CODE REVIEW

**Comment by huneau** [comment]
houuuuuuuuuuaaaaaaaahhhhhhh sooooo nice !!!!!!!!

**Comment by huneau** [comment]
@hjae78 what do you think ?

**Comment by hjae78** [comment]
This is incredible! @Yefancy is it possible to fix this for refined storage as well or does this already do that?

**Comment by Yefancy** [comment]
So far it only works with AE2. i play RS so rarely that i forgot it and ill fix this for RS later.

**Pull request merged**
