### PR TITLE
Fix Naquadah Chain Chemical Reactions

### PR DESCRIPTION
**Pull request by TechLord22**
This PR fixes the naquadah chain chemical reactions in order to fit the new GTCE standards, as well as fix the incorrect reactions in general. All three naquadah types have zero leftover byproducts, and everything is recycled throughout the process as a result of these changes. Most changes are minor formula modifications and outputs. The most "major" change is the Potassium Metabisulfate, which has been replaced with Potassium Peroxymonosulfate - which is a little harder to make, but shouldn't be an issue at LuV. Huge thanks to @DStrand1 for help with figuring out chemical reactions and balancing equations.

### CODE REVIEW

**Comment by huneau** [comment]
you break the mol rules

**Comment by hjae78** [comment]
> you break the mol rules

In the newest version GTCE overhauled how they handled mols, instead of 2 Hydrogen + 1 Oxygen = 3 Water its not 2 Hydrogen + 1 Oxygen = 1 Water. I believe these recipes follow that rule too

**Comment by TechLord22** [comment]
@hjae78 is correct. This process now follows the new mole rules and thus looks different. It does still result in one naquadah compound dust producing one regular dust, so there isn't a buff to naquadah output. But, you no longer loose materials for every naquadah produced which makes the entire process a closed loop. Eventually this will end up being done for every process and this is just the first step.

**Comment by hjae78** [comment]
@huneau for me this is okay, GTCE changed their chemical mol rule and we should follow. We have massive inconsistencies that need to be addressed but this is a good start. As I understand it the amount of recipes you need to complete should be exactly the same, it's just the amount of inputs and outputs being changed which shouldn't change anything

**Comment by DStrand1** [comment]
The Chemistry Changes to GTCE:
https://github.com/GregTechCE/GregTech/pull/1414

I authored these changes, and can vouch for this PR being consistent with what GTCE now follows.

**Comment by hjae78** [comment]
@huneau are we okay to merge this?

**Pull request merged**
